# 100 Practice Problems for Numpy

In [2]:
import numpy as np
import random as rm
arr_example = np.array([1, 2, 3, 4, 5])
print(arr_example)

[1 2 3 4 5]


In [3]:
np.__version__

np.show_config()

{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35225",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.4",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35225",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.31.188.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ucojyb64/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib d

c:\Users\beast\OneDrive - ReachOut\Desktop\Numpy\numpy_100\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [4]:
null_vector = np.zeros(10)
print(null_vector)

# creating a none vector of size 10
none_vector = np.array([None]).repeat(10)
print(none_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[None None None None None None None None None None]


In [5]:
null_vector_size = np.size(null_vector)
print(null_vector_size)

#Using a different function for finding the size of the null vector
null_vector.__sizeof__()

10


192

In [6]:
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#Method 1 with a correct size
vector_10_49 = np.random.randint(9, 50, size=10)
print(vector_10_49)

#Method 2
vector_10_49_2 = np.arange(10,50)
print(vector_10_49_2)

[34 10 29  9 35  9 34 46 30 42]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#Reverse the array
vector_10_49_2[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [9]:
matrix_3x3 = np.arange(0,9).reshape(3,3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
temp_1 = np.array([1,2,0,0,4,0])
zeros = np.where(temp_1 == 0)
print(zeros)

(array([2, 3, 5]),)


In [11]:
Identity_matrix = np.array([1,0,0,0,1,0,0,0,1]).reshape(3,3)
print(Identity_matrix)

#Method 2
identity_matrix = np.identity(3)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
random_matrix = np.random.randint(0, 100, size=27).reshape(3,3,3)
print(random_matrix)

#Method 2
randos = np.random.random((3,3,3))
print(randos)

[[[ 8 97 26]
  [32 47 24]
  [ 6 89 95]]

 [[ 1 41 58]
  [78 60 99]
  [82 97 11]]

 [[11 58 34]
  [40 42 91]
  [13 29 17]]]
[[[0.21481501 0.08386769 0.31772069]
  [0.74332483 0.33769779 0.80170586]
  [0.54077824 0.48775152 0.11261369]]

 [[0.39524464 0.99034753 0.84952021]
  [0.53457526 0.88762167 0.83024708]
  [0.644921   0.06620126 0.52902655]]

 [[0.60382862 0.92742795 0.90983812]
  [0.80681053 0.21184694 0.04112675]
  [0.04120602 0.21121391 0.07634455]]]


In [13]:
randos = np.random.randint(0, 100, size=5)
Sum = 0
for i in randos:
    Sum += i
    print(Sum//30)
else:
    pass

#Method 2
randos.mean()

1
2
4
4
4


np.float64(29.8)

In [14]:
size = rm.randint(2,10)
print(f'The size of the matrix will be {size}')

ones = np.ones((size,size))
zeros = np.zeros((size-2,size-2))

ones[1:len(ones)-1, 1:len(ones)-1] = zeros
print(ones)

The size of the matrix will be 3
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [15]:
# ONly applicable for one dimensional matrix
size = rm.randint(2,10)
arr = np.random.randint(0,10, size=size*size).reshape(size,size)
print(arr)

'''
zeros = np.zeros((size+2,size+2))
print(zeros)

zeros[1,1:-1] = arr
print(zeros)
'''

#method 2
padded = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(padded)

[[6 5 9 4 1 2 4 5]
 [1 8 5 4 6 3 4 4]
 [8 7 5 4 5 7 2 4]
 [3 1 8 5 7 2 8 5]
 [9 9 3 0 8 3 4 3]
 [2 4 0 0 3 2 7 3]
 [1 1 3 6 6 9 9 5]
 [4 5 1 7 0 1 0 6]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 6 5 9 4 1 2 4 5 0]
 [0 1 8 5 4 6 3 4 4 0]
 [0 8 7 5 4 5 7 2 4 0]
 [0 3 1 8 5 7 2 8 5 0]
 [0 9 9 3 0 8 3 4 3 0]
 [0 2 4 0 0 3 2 7 3 0]
 [0 1 1 3 6 6 9 9 5 0]
 [0 4 5 1 7 0 1 0 6 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [17]:
matrix_5x5 = np.random.randint(0,100, size=size*size).reshape(size,size)
arr = np.arange(1, size)

print(matrix_5x5)
print(size)
print(arr)

matrix_5x5[arr, arr-1] = arr
print(matrix_5x5)

[[94 58 43  6 76 48  7 69]
 [62 50 78 23 76 92 64 28]
 [58 54 64 32 23 44 85 18]
 [14 24 95 86 35 45 40 14]
 [52 82 69  5 78 19 57 59]
 [87 37 45  1 17 31 37 60]
 [69 14 52 49 52 35 43 86]
 [ 6 84 29 25 31 68 70 11]]
8
[1 2 3 4 5 6 7]
[[94 58 43  6 76 48  7 69]
 [ 1 50 78 23 76 92 64 28]
 [58  2 64 32 23 44 85 18]
 [14 24  3 86 35 45 40 14]
 [52 82 69  4 78 19 57 59]
 [87 37 45  1  5 31 37 60]
 [69 14 52 49 52  6 43 86]
 [ 6 84 29 25 31 68  7 11]]


In [18]:
#Creating a 8x8 matrix
matric_8x8 = np.array([[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0]])
print(matric_8x8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
print(np.unravel_index(99, (96,7,8)))

(np.int64(1), np.int64(5), np.int64(3))
