# 100 Practice Problems for Numpy

In [ ]:
import numpy as np
arr_example = np.array([1, 2, 3, 4, 5])
print(arr_example)

[1 2 3 4 5]


In [ ]:
np.__version__

np.show_config()

{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35225",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.4",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35225",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.31.188.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ucojyb64/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib d

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

# creating a none vector of size 10
none_vector = np.array([None]).repeat(10)
print(none_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[None None None None None None None None None None]


In [ ]:
null_vector_size = np.size(null_vector)
print(null_vector_size)

#Using a different function for finding the size of the null vector
null_vector.__sizeof__()

10


192

In [ ]:
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#Method 1 with a correct size
vector_10_49 = np.random.randint(9, 50, size=10)
print(vector_10_49)

#Method 2
vector_10_49_2 = np.arange(10,50)
print(vector_10_49_2)

[38 10 20 22 29 46 26 39 34 10]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Reverse the array
vector_10_49_2[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [ ]:
matrix_3x3 = np.arange(0,9).reshape(3,3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
temp_1 = np.array([1,2,0,0,4,0])
zeros = np.where(temp_1 == 0)
print(zeros)

(array([2, 3, 5]),)


In [ ]:
Identity_matrix = np.array([1,0,0,0,1,0,0,0,1]).reshape(3,3)
print(Identity_matrix)

#Method 2
identity_matrix = np.identity(3)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
random_matrix = np.random.randint(0, 100, size=27).reshape(3,3,3)
print(random_matrix)

#Method 2
randos = np.random.random((3,3,3))
print(randos)

[[[43 65 53]
  [ 7 17 29]
  [95 54 68]]

 [[ 7 75 33]
  [61  9  4]
  [98 12 37]]

 [[48 47 64]
  [26  4 35]
  [73 43 79]]]
[[[4.98944306e-01 9.23121156e-01 5.68190254e-01]
  [2.10579997e-01 1.70985281e-02 4.38009556e-01]
  [3.93201231e-01 2.16591561e-01 8.44122232e-01]]

 [[1.67186914e-01 4.15141219e-01 6.51678022e-01]
  [1.21316684e-01 4.89512596e-01 3.27455334e-01]
  [1.51948286e-01 4.80440194e-05 6.98080558e-01]]

 [[4.55862964e-01 2.12101621e-04 9.72810520e-01]
  [9.93287179e-01 1.67851714e-01 2.33424467e-01]
  [8.87898008e-01 2.51743073e-01 2.66357855e-01]]]


In [ ]:
randos = np.random.randint(0, 100, size=5)
Sum = 0
for i in randos:
    Sum += i
    print(Sum//30)
else:
    pass

#Method 2
randos.mean()

0
2
3
4
6
6
9
10
11
13
13
16
18
19
21
22
24
25
26
29
30
32
33
37
38
39
40
41
43
45


np.float64(45.333333333333336)

In [ ]:
arr_2d = np.array([[1,1,1,1,1],[1,1,1,1,1]])
print(arr_2d)