# 100 Practice Problems for Numpy

In [15]:
import numpy as np
import random as rm
arr_example = np.array([1, 2, 3, 4, 5])
print(arr_example)

[1 2 3 4 5]


In [16]:
np.__version__

np.show_config()

{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35225",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.4",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35225",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.31.188.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ucojyb64/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib d

c:\Users\beast\OneDrive - ReachOut\Desktop\Numpy\numpy_100\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [17]:
null_vector = np.zeros(10)
print(null_vector)

# creating a none vector of size 10
none_vector = np.array([None]).repeat(10)
print(none_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[None None None None None None None None None None]


In [18]:
null_vector_size = np.size(null_vector)
print(null_vector_size)

#Using a different function for finding the size of the null vector
null_vector.__sizeof__()

10


192

In [19]:
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [20]:
#Method 1 with a correct size
vector_10_49 = np.random.randint(9, 50, size=10)
print(vector_10_49)

#Method 2
vector_10_49_2 = np.arange(10,50)
print(vector_10_49_2)

[25 21 14 29 14 17 25 11 39 31]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [21]:
#Reverse the array
vector_10_49_2[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [22]:
matrix_3x3 = np.arange(0,9).reshape(3,3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
temp_1 = np.array([1,2,0,0,4,0])
zeros = np.where(temp_1 == 0)
print(zeros)

(array([2, 3, 5]),)


In [24]:
Identity_matrix = np.array([1,0,0,0,1,0,0,0,1]).reshape(3,3)
print(Identity_matrix)

#Method 2
identity_matrix = np.identity(3)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
random_matrix = np.random.randint(0, 100, size=27).reshape(3,3,3)
print(random_matrix)

#Method 2
randos = np.random.random((3,3,3))
print(randos)

[[[80  9 64]
  [57 15 24]
  [87 21 28]]

 [[44 67 75]
  [82 69 60]
  [77 64 42]]

 [[60 43  2]
  [10 50 23]
  [46 16 65]]]
[[[0.36135896 0.04319969 0.75937993]
  [0.33518841 0.99227836 0.85605636]
  [0.30637497 0.44852058 0.97933367]]

 [[0.54632917 0.7764176  0.02406662]
  [0.58831955 0.86430057 0.1033234 ]
  [0.43070876 0.44269798 0.07511808]]

 [[0.36356759 0.00140928 0.9410341 ]
  [0.50106292 0.80491221 0.39080937]
  [0.5742331  0.1268139  0.72564733]]]


In [26]:
randos = np.random.randint(0, 100, size=5)
Sum = 0
for i in randos:
    Sum += i
    print(Sum//30)
else:
    pass

#Method 2
randos.mean()

3
4
6
9
11


np.float64(67.6)

In [ ]:
size = rm.randint(2,10)
print(f'The size of the matrix will be {size}')

ones = np.ones((size,size))
zeros = np.zeros((size-2,size-2))

ones[1:len(ones)-1, 1:len(ones)-1] = zeros
print(ones)

The size of the matrix will be 2
[[1. 1.]
 [1. 1.]]


In [178]:
# ONly applicable for one dimensional matrix
size = rm.randint(2,10)
arr = np.random.randint(0,10, size=size*size).reshape(size,size)
print(arr)

'''
zeros = np.zeros((size+2,size+2))
print(zeros)

zeros[1,1:-1] = arr
print(zeros)
'''

#method 2
padded = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(padded)

[[6 8 4 4 1 3 2 9 9]
 [6 3 3 8 2 6 4 3 6]
 [4 6 5 9 5 2 1 5 4]
 [4 6 8 1 8 1 7 8 8]
 [1 0 2 4 2 1 9 5 2]
 [8 5 1 2 5 9 1 5 8]
 [9 7 2 4 2 8 8 7 0]
 [7 2 9 0 4 3 6 3 8]
 [4 9 3 3 4 6 2 5 2]]
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 6 8 4 4 1 3 2 9 9 0]
 [0 6 3 3 8 2 6 4 3 6 0]
 [0 4 6 5 9 5 2 1 5 4 0]
 [0 4 6 8 1 8 1 7 8 8 0]
 [0 1 0 2 4 2 1 9 5 2 0]
 [0 8 5 1 2 5 9 1 5 8 0]
 [0 9 7 2 4 2 8 8 7 0 0]
 [0 7 2 9 0 4 3 6 3 8 0]
 [0 4 9 3 3 4 6 2 5 2 0]
 [0 0 0 0 0 0 0 0 0 0 0]]
